# -*- coding: utf-8 -*-
"""Course Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ewm3dfc_x66FEFHYt_jq4H0bPw8idOz0
"""

# Installations 
!pip install xlsxwriter
!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import sys
import time
import xlsxwriter
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

# Setup excel or database here.
workbook = xlsxwriter.Workbook('Course_Data.xlsx')
worksheet = workbook.add_worksheet()

row = 0;
column = 0;

# Functions that grabs correct elements from the dynamic web-page.
def pullData(url):
 
  global row
  global column

  driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
  driver.get(url)

  list = driver.find_elements(By.CLASS_NAME, "course-row")

  for l in list:

    # Grabs inital information from each of the rows in the table.
    courseCode = l.find_element(By.CLASS_NAME, "course-code").text
    courseName = l.find_element(By.CLASS_NAME, "title").text
    duration = l.find_element(By.CLASS_NAME, "duration").text
    days = l.find_element(By.CLASS_NAME, "days").text
    times = l.find_element(By.CLASS_NAME, "time").text
    classType = l.find_element(By.CLASS_NAME, "type").text
    
    # Opens current row.
    l.click()
    driver.implicitly_wait(2)
    time.sleep(2)

    format = 'No Format Found'
    prerequisites = 'No Prerequisites Found'
    restrictions = 'No Restrictions Found'
    exclusions = 'No Exclusions Found'
    notes = 'No Notes Found'
    instructor = ''
    fullDuration = ''
    courseDays = ''
    location = ''

    # Grabs remaining details within the left side of drop-down. 
    description = l.find_element(By.CLASS_NAME, 'page-intro').text
    left = l.find_element(By.CLASS_NAME, 'description')

    try:
      formatTitle = left.find_element(By.XPATH,"..//strong[contains(text(),'Format:')]")
      formatInfo = formatTitle.find_element(By.XPATH, "..");
      format = formatInfo.text
    except:
      print('No Format Found')
    
    try:
      restrictionsTitle = left.find_element(By.XPATH,"..//strong[contains(text(),'Restrictions:')]")
      restrictionsInfo = restrictionsTitle.find_element(By.XPATH, "./..");
      restrictions = restrictionsInfo.text
    except:
      print('No Restrictions Found')

    try:
      exclusionsTitle = left.find_element(By.XPATH,"..//strong[contains(text(),'Exclusions:')]")
      exclusionsInfo = exclusionsTitle.find_element(By.XPATH, "./..");
      exclusions = exclusionsInfo.text
    except:
      print('No Exclusions Found')

    try:
      notesTitle = left.find_element(By.XPATH,"..//strong[contains(text(),'Notes:')]")
      notesInfo = notesTitle.find_element(By.XPATH, "./..");
      notes = notesInfo.text
    except:
      print('No Notes Found')

    try:
      prerequisitesTitle = left.find_element(By.XPATH,"..//strong[contains(text(),'Prerequisites:')]")
      prerequisitesInfo = prerequisitesTitle.find_element(By.XPATH, "./..");
      prerequisites = prerequisitesInfo.text
    except:
      print('No Prerequisites Found')


    # Grabing information from right side on drop down. 
    right = l.find_element(By.CLASS_NAME, 'vitals')

    try:
      coursecal = right.find_element(By.CLASS_NAME, 'coursecal')
      days = coursecal.find_elements(By.TAG_NAME, 'td')

      temp = 0;

      for day in days:
          if day.get_attribute("class") == 'active':
            if temp == 0: courseDays = courseDays + "Sunday, "
            if temp == 1: courseDays = courseDays + "Monday, "
            if temp == 2: courseDays = courseDays + "Tuesday, "
            if temp == 3: courseDays = courseDays + "Wednesday, "
            if temp == 4: courseDays = courseDays + "Thursday, "
            if temp == 5: courseDays = courseDays + "Friday, "
            if temp == 6: courseDays = courseDays + "Saturday, "
          temp = temp + 1
          
    except:
      print('No Days Found')

    try:
      instructorTitle = right.find_element(By.XPATH,"..//strong[contains(text(),'Instructor:')]")
      instructorInfo = instructorTitle.find_element(By.XPATH, "./..");
      instructor = instructorInfo.text
    except:
      print('No Instructor Found')

    try:
      fullDurationTitle = right.find_element(By.XPATH,"..//strong[contains(text(),'Duration:')]")
      fullDurationInfo = fullDurationTitle.find_element(By.XPATH, "./..");
      fullDuration = fullDurationInfo.text
    except:
      print('No Full Duration Found')

    try:
      locationTitle = right.find_element(By.XPATH,"..//strong[contains(text(),'Location:')]")
      locationInfo = locationTitle.find_element(By.XPATH, "./..");
      location = locationInfo.text
    except:
      print('No Location Found')


    # Write to excel sheet or database.
    worksheet.write(row, column, courseCode)
    column = column + 1
    worksheet.write(row, column, courseName)
    column = column + 1
    worksheet.write(row, column, description)
    column = column + 1
    worksheet.write(row, column, duration)
    column = column + 1
    worksheet.write(row, column, fullDuration)
    column = column + 1
    worksheet.write(row, column, instructor)
    column = column + 1
    worksheet.write(row, column, location)
    column = column + 1
    worksheet.write(row, column, format)
    column = column + 1
    worksheet.write(row, column, restrictions)
    column = column + 1
    worksheet.write(row, column, prerequisites)
    column = column + 1
    worksheet.write(row, column, exclusions)
    column = column + 1
    worksheet.write(row, column, notes)
    column = column + 1
    worksheet.write(row, column, courseDays)
    column = column + 1
    worksheet.write(row, column, times)
    column = column + 1
    worksheet.write(row, column, classType)
    column = 0
    row = row + 1

programDriver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)
programDriver.get('https://brocku.ca/guides-and-timetables/timetables/?session=fw&type=ug&level=all')

# Grabs a list of programs at Brock.
programs = programDriver.find_elements(By.CLASS_NAME, "code")

for l in programs:
  url = "https://brocku.ca/guides-and-timetables/timetables/?session=FW&type=UG&level=All&program=" + l.text
  pullData(url)

workbook.close()











